import { readFileSync } from "node:fs";

const html = readFileSync(new URL("./index.html", import.meta.url), "utf8");

const checks = [
  ["font selector exists", /id="fontSelect"/],
  ["color theme selector exists", /id="colorThemeSelect"/],
  ["font size selector exists", /id="fontSizeSelect"/],
  ["line height selector exists", /id="lineHeightSelect"/],
  ["module gap selector exists", /id="moduleGapSelect"/],
  ["font family data field exists", /fontFamily:/],
  ["color theme data field exists", /colorTheme:/],
  ["font scale data field exists", /fontScale:/],
  ["line height data field exists", /lineHeight:/],
  ["module gap data field exists", /moduleGap:/],
  ["hidden sections data field exists", /hiddenSections:/],
  ["resume font CSS variable exists", /--resume-font/],
  ["resume theme primary CSS variable exists", /--theme-primary/],
  ["resume theme soft CSS variable exists", /--theme-soft/],
  ["resume font size CSS variable exists", /--resume-scale/],
  ["resume line height CSS variable exists", /--resume-line-height/],
  ["resume module gap CSS variable exists", /--resume-module-gap/],
  ["name font scales", /\.r-name\s*\{[\s\S]*font-size:\s*calc\(24px \* var\(--resume-scale\)\)/],
  ["body font scales", /\.r-body\s*\{[\s\S]*font-size:\s*calc\(10px \* var\(--resume-scale\)\)/],
  ["body line height uses setting", /\.r-body\s*\{[\s\S]*line-height:\s*var\(--resume-line-height\)/],
  ["list line height uses setting", /\.resume li\s*\{[\s\S]*line-height:\s*var\(--resume-line-height\)/],
  ["list item gap uses module gap setting", /\.resume li\s*\{[\s\S]*margin:\s*0 0 var\(--resume-module-gap\) 0/],
  ["resume item gap uses module gap setting", /\.r-item\s*\{[\s\S]*margin-bottom:\s*calc\(4\.3mm \+ var\(--resume-module-gap\)\)/],
  ["section title font scales", /\.r-section-title\s*\{[\s\S]*font-size:\s*calc\(12px \* var\(--resume-scale\)\)/],
  ["font size uses Chinese type size labels", /<option value="1">五号<\/option>/],
  ["font size has xiaosi option", /<option value="1\.08">小四<\/option>/],
  ["font size has sihao option", /<option value="1\.16">四号<\/option>/],
  ["color theme has blue option", /<option value="blue">颜色 蓝色<\/option>/],
  ["color theme has burgundy option", /<option value="burgundy">颜色 酒红<\/option>/],
  ["color theme palette helper exists", /function getColorTheme/],
  ["color theme selector updates data", /colorThemeSelect"[\s\S]*data\.colorTheme\s*=\s*event\.target\.value/],
  ["preview applies theme primary", /setProperty\("--theme-primary",\s*theme\.primary\)/],
  ["preview applies theme soft", /setProperty\("--theme-soft",\s*theme\.soft\)/],
  ["line height has 12pt option", /<option value="12pt">行距 12 磅<\/option>/],
  ["line height has 16pt option", /<option value="16pt">行距 16 磅<\/option>/],
  ["line height has 10pt option", /<option value="10pt">行距 10 磅<\/option>/],
  ["line height has 24pt option", /<option value="24pt">行距 24 磅<\/option>/],
  ["module gap has zero option", /<option value="0pt">模块内距 0 磅<\/option>/],
  ["module gap has 10pt option", /<option value="10pt">模块内距 10 磅<\/option>/],
  ["line height stores pt values", /lineHeight:\s*"14pt"/],
  ["module gap stores pt values", /moduleGap:\s*"2pt"/],
  ["legacy numeric line height is normalized to pt", /function normalizeLineHeight[\s\S]*"1\.38":\s*"14pt"/],
  ["module gap normalizer exists", /function normalizeModuleGap/],
  ["line height selector updates data", /lineHeightSelect"[\s\S]*data\.lineHeight\s*=\s*event\.target\.value/],
  ["module gap selector updates data", /moduleGapSelect"[\s\S]*data\.moduleGap\s*=\s*event\.target\.value/],
  ["preview applies line height setting", /setProperty\("--resume-line-height",\s*normalizeLineHeight\(data\.lineHeight\)/],
  ["preview applies module gap setting", /setProperty\("--resume-module-gap",\s*normalizeModuleGap\(data\.moduleGap\)/],
  ["preview zoom selector exists", /id="previewZoomSelect"/],
  ["finance template option exists", /<option value="finance">金融稳重简历<\/option>/],
  ["compact template option exists", /<option value="compact">紧凑投递简历<\/option>/],
  ["academic template option exists", /<option value="academic">学术科研简历<\/option>/],
  ["banner template option exists", /<option value="banner">商务横幅简历<\/option>/],
  ["teal template option exists", /<option value="teal">青绿清爽简历<\/option>/],
  ["finance template style exists", /\.template-finance/],
  ["compact template style exists", /\.template-compact/],
  ["academic template style exists", /\.template-academic/],
  ["banner template style exists", /\.template-banner/],
  ["teal template style exists", /\.template-teal/],
  ["preview zoom data field exists", /previewZoom:/],
  ["default links use one link per line", /links:\s*"....\\n....\\n...."/],
  ["links editor is multiline", /textarea\("链接 \/ 作品集",\s*"basic\.links"/],
  ["links preview renderer exists", /function linksHtml/],
  ["paragraph renderer exists", /function paragraphHtml/],
  ["paragraph renderer preserves new lines", /lines\(value\)\.map\(line => `<p class="r-body">\$\{esc\(line\)\}<\/p>`\)\.join\(""\)/],
  ["summary uses paragraph renderer", /paragraphHtml\(data\.basic\.summary\)/],
  ["legacy slash-separated links are normalized", /function normalizeLinks[\s\S]*split\(\s*\/\\s\+\\\/\\s\+\/\s*\)/],
  ["loaded resume data normalizes links", /return normalizeData\(/],
  ["section delete button exists", /data-action="delete-section"/],
  ["section restore button exists", /data-action="restore-section"/],
  ["hidden sections helper exists", /function isSectionVisible/],
  ["delete section helper exists", /function deleteSection/],
  ["restore section helper exists", /function restoreSection/],
  ["render editor skips hidden sections", /isSectionVisible\("education"\) \? renderRepeatableEditor/],
  ["main preview skips hidden sections", /ifSection\("education"/],
  ["section delete click is handled", /action === "delete-section"/],
  ["section restore click is handled", /action === "restore-section"/],
  ["repeatable entries have move up button", /data-action="move-entry-up"/],
  ["repeatable entries have move down button", /data-action="move-entry-down"/],
  ["first entry disables move up", /index === 0 \? "disabled" : ""/],
  ["last entry disables move down", /index === items\.length - 1 \? "disabled" : ""/],
  ["move entry helper exists", /function moveEntry/],
  ["move entry swaps items", /\[items\[index\], items\[nextIndex\]\]\s*=\s*\[items\[nextIndex\], items\[index\]\]/],
  ["move up click is handled", /action === "move-entry-up"/],
  ["move down click is handled", /action === "move-entry-down"/],
  ["custom default storage key exists", /CUSTOM_DEFAULT_KEY/],
  ["set default example button exists", /id="setDefaultBtn"/],
  ["default data helper exists", /function getDefaultData/],
  ["reset uses saved default example", /data\s*=\s*getDefaultData\(\)/],
  ["set default saves current resume", /localStorage\.setItem\(CUSTOM_DEFAULT_KEY,\s*JSON\.stringify\(data\)\)/],
  ["preview zoom CSS variable exists", /--preview-zoom/],
  ["preview stack scales by zoom", /transform:\s*scale\(var\(--preview-zoom\)\)/],
  ["print resets preview zoom", /--preview-zoom:\s*1/],
  ["preview applies resume settings", /applyResumeSettings/],
  ["pagination keep together class exists", /class="r-item keep-together"/],
  ["print avoids splitting items", /break-inside:\s*avoid/],
  ["legacy page break protection exists", /page-break-inside:\s*avoid/],
  ["section heading stays with content", /break-after:\s*avoid/],
  ["preview page keeps 1:1 scale", /\.resume\s*\{[\s\S]*width:\s*210mm[\s\S]*min-height:\s*297mm/],
  ["responsive view does not scale resume", !/scale\(\.82\)/.test(html)],
  ["resume stack exists", /class="resume-stack"\s+id="resumePreview"/],
  ["pagination function exists", /function paginateBlocks/],
  ["page height is fixed A4", /height:\s*297mm/],
  ["print forces each page break", /break-after:\s*page/],
  ["body is constrained to viewport", /body\s*\{[\s\S]*overflow:\s*hidden/],
  ["app uses viewport height", /\.app\s*\{[\s\S]*height:\s*100vh/],
  ["workspace columns are viewport constrained", /grid-template-columns:\s*minmax\(0,\s*1fr\)\s*minmax\(0,\s*1fr\)/],
  ["workspace does not overflow page", /\.workspace\s*\{[\s\S]*overflow:\s*hidden/],
  ["workspace width is constrained", /\.workspace\s*\{[\s\S]*max-width:\s*100%/],
  ["editor width is constrained", /\.editor\s*\{[\s\S]*max-width:\s*100%/],
  ["preview width is constrained", /\.preview-wrap\s*\{[\s\S]*max-width:\s*100%/],
  ["toolbar stays horizontal", /\.toolbar\s*\{[\s\S]*flex-wrap:\s*nowrap/],
  ["toolbar scrolls internally", /\.toolbar\s*\{[\s\S]*overflow-x:\s*auto/],
  ["toolbar cannot widen page", /\.toolbar\s*\{[\s\S]*max-width:\s*100%/],
  ["file button uses normal toolbar font weight", /\.file-btn\s*\{[\s\S]*font-weight:\s*400/],
  ["file button uses toolbar font size", /\.file-btn\s*\{[\s\S]*font-size:\s*14px/],
  ["file button uses inline flex layout", /\.file-btn\s*\{[\s\S]*display:\s*inline-flex/],
  ["editor can scroll internally", /\.editor\s*\{[\s\S]*overflow:\s*auto/],
  ["preview can scroll internally", /\.preview-wrap\s*\{[\s\S]*overflow:\s*auto/],
];

let failed = false;
for (const [name, pattern] of checks) {
  const passed = typeof pattern === "boolean" ? pattern : pattern.test(html);
  if (!passed) {
    console.error(`FAIL ${name}`);
    failed = true;
  } else {
    console.log(`PASS ${name}`);
  }
}

if (failed) process.exit(1);
